import Head from 'next/head'
import Layout from "@/Layout";
import * as Styled from './styles'
import { User } from '@phosphor-icons/react';
import { theme } from '@/styles/stitches.config';
import { useState } from 'react';
import { BookCardReduce } from '@/components/Book/BookCardReduce';
import { recentReviews } from '../home/utils/book';
import { SearchInput } from '@/components/SearchInput';
import { User as UserComponent } from './components/User';


export default function Profile() {
  const [filterSelected, setFilterSelected] = useState('Tudo')
  const { colors } = theme

  return (
    <>
      <Head>
        <title>Profile | Book Wise</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Layout>
        {/* Header */}
        <Styled.Header>
          <User size={32} color={colors.green100.value} />
          <h1>Profile</h1>
        </Styled.Header>

        {/* Cards */}
        <Styled.Container>

          <Styled.Content>
            <Styled.Search>
              <SearchInput placeholder='Buscar livro ou autor' />
            </Styled.Search>

            <Styled.ExplorerBooks>
              {recentReviews.map(pub => (
                <BookCardReduce key={pub.id} book={pub.book} />
              ))}
            </Styled.ExplorerBooks>
          </Styled.Content>

          <Styled.Aside>
            <UserComponent />
          </Styled.Aside>
        </Styled.Container>
      </Layout>

    </>
  )
}