import Head from 'next/head'

import * as Styled from './styles'

import { Navbar } from '@/components/Navbar'

export default function Home() {
  return (
    <>
      <Head>
        <title>Home | Book Wise</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Styled.Container>
        <Navbar />

        <Styled.Content>
          fdsfsdf

          
        </Styled.Content>
      </Styled.Container>
    </>
  )
}
