import Head from 'next/head'
import Layout from "@/components/Layout";
import * as Styled from './styles'
import { Binoculars } from '@phosphor-icons/react';
import { theme } from '@/styles/stitches.config';
import { bookFilters } from './utils/books-filters';
import { useState } from 'react';
import { BookCardReduce } from '@/components/Book/BookCardReduce';
import { recentReviews } from '../home/utils/book';
import { SearchInput } from '@/components/SearchInput';

export default function Explore() {
  const [filterSelected, setFilterSelected] = useState('Tudo')
  const { colors } = theme

  return (
    <>
      <Head>
        <title>Explorar | Book Wise</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Layout>
        {/* Header */}
        <Styled.Header>
          <Binoculars size={32} color={colors.green100.value} />
          <h1>Explorar</h1>
        </Styled.Header>

        <Styled.Search >
          <SearchInput placeholder='Buscar livro ou autor' />
        </Styled.Search>
        
        {/* Filters */}
        <Styled.FiltersContainer>
          {bookFilters.map(filter => (
            <Styled.Filter
              key={filter}
              isSelected={filterSelected === filter}
              onClick={() => setFilterSelected(filter)}
            >
              {filter}
            </Styled.Filter>
          ))}
        </Styled.FiltersContainer>

        {/* Cards */}
        <Styled.ExplorerBooks>
          {recentReviews.map(pub => (
            <BookCardReduce key={pub.id} book={pub.book} />
          ))}
        </Styled.ExplorerBooks>
      </Layout>

    </>
  )
}